/**
 * Character Metadata Utilities
 *
 * Provides pinyin and word examples for Chinese characters.
 * Pinyin is generated by the pinyin-pro library which covers
 * all CJK characters across Unicode planes.
 * Word examples come from a built-in curated dataset.
 */

import { pinyin, polyphonic } from 'pinyin-pro'
import type { WordBook } from '../core/types'

interface CharInfo {
  pinyin: string
  words: string[]
}

/**
 * Built-in word example database.
 * Contains common elementary school characters with curated word examples.
 * Pinyin is NOT stored here — it's always generated via pinyin-pro for accuracy.
 */
const WORD_DATABASE: Record<string, string[]> = {
  '一': ['一个', '第一', '唯一'],
  '二': ['二月', '第二', '二手'],
  '三': ['三月', '再三', '三角'],
  '四': ['四月', '四周', '四季'],
  '五': ['五月', '五星', '五彩'],
  '六': ['六月', '六角', '六艺'],
  '七': ['七月', '七夕', '七彩'],
  '八': ['八月', '八方', '八成'],
  '九': ['九月', '九霄', '九牛'],
  '十': ['十月', '十足', '十年'],
  '上': ['上学', '上升', '上下'],
  '下': ['下午', '下雨', '下课'],
  '大': ['大人', '大家', '大小'],
  '小': ['小孩', '小心', '小学'],
  '人': ['人们', '人生', '人口'],
  '口': ['门口', '口水', '开口'],
  '手': ['手机', '手工', '洗手'],
  '日': ['日出', '日月', '生日'],
  '月': ['月亮', '月光', '明月'],
  '水': ['水果', '水面', '河水'],
  '火': ['火车', '火光', '大火'],
  '山': ['山上', '山水', '高山'],
  '石': ['石头', '石子', '宝石'],
  '田': ['田地', '田野', '农田'],
  '木': ['木头', '树木', '草木'],
  '草': ['草地', '草原', '青草'],
  '鸟': ['鸟儿', '小鸟', '飞鸟'],
  '虫': ['虫子', '昆虫', '小虫'],
  '鱼': ['鱼儿', '金鱼', '钓鱼'],
  '天': ['天空', '今天', '明天'],
  '地': ['地方', '地图', '大地'],
  '风': ['风吹', '大风', '风景'],
  '雨': ['下雨', '雨伞', '暴雨'],
  '云': ['白云', '乌云', '云朵'],
  '雪': ['雪花', '下雪', '白雪'],
  '中': ['中国', '中心', '中午'],
  '国': ['国家', '中国', '外国'],
  '学': ['学习', '学生', '学校'],
  '生': ['生活', '学生', '生日'],
  '字': ['字体', '汉字', '名字'],
  '书': ['书本', '读书', '书包'],
  '好': ['你好', '好事', '好看'],
  '不': ['不是', '不好', '不同'],
  '白': ['白色', '白天', '明白'],
  '红': ['红色', '红花', '火红'],
  '来': ['回来', '过来', '未来'],
  '去': ['回去', '出去', '过去'],
  '走': ['走路', '行走', '走动'],
  '跑': ['跑步', '奔跑', '跑车'],
  '看': ['看见', '看书', '好看'],
  '听': ['听见', '听话', '听力'],
  '说': ['说话', '听说', '小说'],
  '写': ['写字', '书写', '写作'],
  '读': ['读书', '阅读', '朗读'],
  '坐': ['坐下', '乘坐', '坐车'],
  '立': ['站立', '立即', '独立'],
  '见': ['看见', '再见', '见面'],
  '门': ['门口', '大门', '开门'],
  '马': ['马上', '白马', '骑马'],
  '牛': ['牛奶', '小牛', '水牛'],
  '羊': ['山羊', '羊毛', '白羊'],
  '左': ['左边', '左手', '左右'],
  '右': ['右边', '右手', '左右'],
  '前': ['前面', '前天', '前进'],
  '后': ['后面', '后天', '后来'],
  '多': ['多少', '很多', '许多'],
  '少': ['多少', '少量', '少年'],
  '男': ['男孩', '男人', '男生'],
  '女': ['女孩', '女人', '女生'],
  '爸': ['爸爸', '老爸'],
  '妈': ['妈妈', '老妈'],
  '哥': ['哥哥', '大哥', '表哥'],
  '弟': ['弟弟', '小弟', '兄弟'],
  '姐': ['姐姐', '大姐', '姐妹'],
  '妹': ['妹妹', '小妹', '姐妹'],
  '家': ['家人', '回家', '大家'],
  '爱': ['爱心', '可爱', '热爱'],
  '笑': ['笑声', '微笑', '大笑'],
  '哭': ['哭泣', '大哭', '哭声'],
  '春': ['春天', '春风', '春节'],
  '夏': ['夏天', '盛夏', '立夏'],
  '秋': ['秋天', '秋风', '中秋'],
  '冬': ['冬天', '寒冬', '立冬'],
  '早': ['早上', '早晨', '早安'],
  '晚': ['晚上', '夜晚', '晚安'],
  '星': ['星星', '星光', '星球'],
  '阳': ['太阳', '阳光', '夕阳'],
  '光': ['光芒', '灯光', '光明'],
  '河': ['河水', '小河', '黄河'],
  '海': ['大海', '海水', '海洋'],
  '江': ['江水', '长江', '江边'],
  '湖': ['湖水', '湖泊', '江湖'],
  '叶': ['叶子', '树叶', '红叶'],
}

/**
 * Error thrown by validation functions when user input is invalid.
 * Distinguishable from system errors (IndexedDB, network) so callers
 * can silently skip validation failures while surfacing real problems.
 */
export class ValidationError extends Error {
  constructor(message: string) {
    super(message)
    this.name = 'ValidationError'
  }
}

/**
 * Check whether a single character is a Chinese (Han) character.
 * Uses Unicode property escapes to cover all CJK planes,
 * including Extension A–G in supplementary planes.
 */
export function isChineseChar(char: string): boolean {
  if (!char || char.length === 0) return false
  // \p{Script=Han} matches all Han characters across all Unicode planes
  return /^\p{Script=Han}$/u.test(char)
}

/**
 * Validate that a character can be added to a word book.
 * Throws if the character is not Chinese or already exists in the book.
 */
export function validateAddChar(character: string, wordBook: WordBook): void {
  if (!isChineseChar(character)) {
    throw new ValidationError(`"${character}" 不是汉字，不能添加到生字本`)
  }
  if (wordBook.characters.includes(character)) {
    throw new ValidationError(`"${character}" 已在生字本中，不能重复添加`)
  }
}

/**
 * Get pinyin for a single Chinese character using pinyin-pro library.
 * For polyphonic characters (多音字), returns all readings joined by " · ".
 * Covers all CJK characters — no more '?' fallback.
 */
export function getPinyin(char: string): string {
  const readings = polyphonic(char)[0]
  if (!readings) return pinyin(char) // fallback for non-Han chars
  return readings.split(' ').join(' · ')
}

/**
 * Get character information (pinyin + words).
 * Pinyin is always generated via pinyin-pro. Polyphonic characters
 * show all readings separated by " · ".
 * Words come from the built-in curated dataset.
 */
export function getCharInfo(char: string): CharInfo {
  return {
    pinyin: getPinyin(char),
    words: WORD_DATABASE[char] ?? [],
  }
}

/**
 * Get example words for a character.
 */
export function getWords(char: string): string[] {
  return WORD_DATABASE[char] ?? []
}
