/**
 * Import & Compact Pipeline Test
 *
 * Reads snapshot.json + log.jsonl generated by convert.go,
 * replays the log using the app's real replayLog() function,
 * compacts into a new snapshot using createSnapshot(),
 * and writes the result back to ~/work/jihanzi/.
 */
import { describe, it, expect } from 'vitest'
import { replayLog, createSnapshot } from './log'
import { getChildStats } from './scheduler'
import type { Snapshot, AnyLogEntry, ReviewEntry } from './types'
import * as fs from 'fs'
import * as path from 'path'

const WORK_DIR = path.resolve(process.env.HOME!, 'work/jihanzi')

function readSnapshot(): Snapshot | null {
  const p = path.join(WORK_DIR, 'snapshot.json')
  if (!fs.existsSync(p)) return null
  return JSON.parse(fs.readFileSync(p, 'utf-8')) as Snapshot
}

function readLogs(): AnyLogEntry[] {
  const p = path.join(WORK_DIR, 'log.jsonl')
  if (!fs.existsSync(p)) return []
  const content = fs.readFileSync(p, 'utf-8')
  return content
    .split('\n')
    .filter(l => l.trim())
    .map(l => JSON.parse(l) as AnyLogEntry)
}

describe('Import & Compact Pipeline', () => {
  it('replays log against snapshot and creates compacted snapshot', () => {
    // 1. Read input
    const snapshot = readSnapshot()
    const logs = readLogs()

    expect(snapshot).not.toBeNull()
    expect(logs.length).toBeGreaterThan(0)

    console.log(`Snapshot timestamp: ${snapshot!.timestamp}`)
    console.log(`Log entries: ${logs.length}`)

    // Verify base state is clean (empty progress)
    const baseChild = snapshot!.state.children[0]
    expect(baseChild.name).toBe('陈尚恩')
    expect(baseChild.nextCharIndex).toBe(0)
    expect(Object.keys(baseChild.progress)).toHaveLength(0)
    console.log(`Base state: child="${baseChild.name}", progress=empty, nextCharIndex=0 ✓`)

    const wb = snapshot!.state.wordBooks[0]
    expect(wb.name).toBe('Dragon Chill')
    console.log(`WordBook: "${wb.name}", ${wb.characters.length} characters ✓`)

    // 2. Replay log
    const state = replayLog(snapshot, logs)
    console.log(`\nReplayed state:`)
    console.log(`  Children: ${state.children.length}`)
    const child = state.children[0]
    console.log(`  ${child.name}: ${Object.keys(child.progress).length} learned, nextCharIndex=${child.nextCharIndex}`)

    // 3. Verify replay results
    expect(state.children).toHaveLength(1)
    const learnedCount = Object.keys(child.progress).length
    expect(learnedCount).toBe(275)
    expect(child.nextCharIndex).toBe(275)

    // Verify lastGrade is preserved
    const dChars = findCharsByGrade(logs as ReviewEntry[], 'd')
    expect(dChars.length).toBeGreaterThan(0)
    const dSm2 = child.progress[dChars[0]]
    expect(dSm2!.lastGrade).toBe('d')
    console.log(`  Grade-d char "${dChars[0]}": lastGrade=${dSm2!.lastGrade} ✓`)

    const bChars = findCharsByGrade(logs as ReviewEntry[], 'b')
    expect(bChars.length).toBeGreaterThan(0)
    expect(child.progress[bChars[0]]!.lastGrade).toBe('b')

    const cChars = findCharsByGrade(logs as ReviewEntry[], 'c')
    expect(cChars.length).toBeGreaterThan(0)
    expect(child.progress[cChars[0]]!.lastGrade).toBe('c')

    // Verify getChildStats correctly counts all grades
    const stats = getChildStats(child)
    expect(stats.a).toBeGreaterThan(0)
    expect(stats.b).toBeGreaterThan(0)
    expect(stats.c).toBeGreaterThan(0)
    expect(stats.d).toBeGreaterThan(0)
    console.log(`  Stats after fix: a=${stats.a} b=${stats.b} c=${stats.c} d=${stats.d} ✓`)

    // 4. Create compacted snapshot
    const compacted = createSnapshot(state)
    console.log(`\nCompacted snapshot timestamp: ${compacted.timestamp}`)

    // 5. Verify round-trip
    const replayedAgain = replayLog(compacted, [])
    expect(Object.keys(replayedAgain.children[0].progress)).toHaveLength(learnedCount)
    // Stats should be identical after round-trip
    const statsAgain = getChildStats(replayedAgain.children[0])
    expect(statsAgain).toEqual(stats)
    console.log(`Round-trip verification: ✓`)

    // 6. Write compacted snapshot
    const outPath = path.join(WORK_DIR, 'snapshot_compacted.json')
    fs.writeFileSync(outPath, JSON.stringify(compacted, null, 2), 'utf-8')
    console.log(`\nWrote ${outPath} (${fs.statSync(outPath).size} bytes)`)

    // 7. Summary
    const unlearned = wb.characters.length - learnedCount
    console.log(`\n=== Pipeline Summary ===`)
    console.log(`Input:  snapshot (empty progress) + ${logs.length} log entries`)
    console.log(`Replay: ${learnedCount} learned, ${unlearned} unlearned`)
    console.log(`Stats:  a=${stats.a} b=${stats.b} c=${stats.c} d=${stats.d}`)
    console.log(`Output: snapshot_compacted.json`)
  })
})

function findCharsByGrade(logs: ReviewEntry[], grade: string): string[] {
  const chars = new Set<string>()
  for (const entry of logs) {
    if (entry.type === 'review' && entry.grade === grade) {
      chars.add(entry.character)
    }
  }
  return [...chars]
}
